// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9PmfNL1A2y_2uSiTRipkzey-GXzNh2q0',
    appId: '1:1006331145454:web:2b24661f8a9b9a2f42d7ff',
    messagingSenderId: '1006331145454',
    projectId: 'ceyizapp-30dff',
    authDomain: 'ceyizapp-30dff.firebaseapp.com',
    storageBucket: 'ceyizapp-30dff.firebasestorage.app',
    measurementId: 'G-GGWXLN50HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgEj0FJMwjGAJz7w6EaEj5rQyTWmP7Ry0',
    appId: '1:1006331145454:android:46078402ac97c40142d7ff',
    messagingSenderId: '1006331145454',
    projectId: 'ceyizapp-30dff',
    storageBucket: 'ceyizapp-30dff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxX71JuQpRXFCkkxhVgn0b86FYn9hFouM',
    appId: '1:1006331145454:ios:0a201e82724b305042d7ff',
    messagingSenderId: '1006331145454',
    projectId: 'ceyizapp-30dff',
    storageBucket: 'ceyizapp-30dff.firebasestorage.app',
    iosBundleId: 'com.example.ceyizappClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxX71JuQpRXFCkkxhVgn0b86FYn9hFouM',
    appId: '1:1006331145454:ios:0a201e82724b305042d7ff',
    messagingSenderId: '1006331145454',
    projectId: 'ceyizapp-30dff',
    storageBucket: 'ceyizapp-30dff.firebasestorage.app',
    iosBundleId: 'com.example.ceyizappClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9PmfNL1A2y_2uSiTRipkzey-GXzNh2q0',
    appId: '1:1006331145454:web:2e9e714063c5ab1d42d7ff',
    messagingSenderId: '1006331145454',
    projectId: 'ceyizapp-30dff',
    authDomain: 'ceyizapp-30dff.firebaseapp.com',
    storageBucket: 'ceyizapp-30dff.firebasestorage.app',
    measurementId: 'G-XM1G6BRFMD',
  );

}